### ISSUE TITLE
Big Sur tracking bug

### ISSUE THREAD

**Issue by nieder** [fink/fink#206]
This is to track issues that exist with the Big Sur betas:

- [x] New arch field for arm64 (#207)
- [x] New macos11 SDK discovery (#208)
- [x] macOS version is now 11.0, not 10.16. (#209)
- [x] new kernel version 20 (#210)
- [x] /usr/bin/perl is now 5.28.2
- [x] gperf-3.0.4 (part of libiconv build) FTBFS with Xcode12
- [x] java detection is broken (#218)

**Comment by nieder** [comment]
Packages that need to be synced between dpkg1.16 and dists.

- [ ] base-files (need new release too for 11.0)
- [ ] bzip2 (upgrade to latest?)
- [ ] debianutils
- [ ] expat1
- [ ] gettext-tools
- [ ] gzip
- [ ] libgettext8-shlibs
- [ ] libiconv
- [ ] libncursesw5.info
- [ ] ncurses
- [ ] objtools
- [ ] sensible-utils
- [ ] tar
- [ ] texinfo
- [ ] time-date-pm
- [ ] unzip
- [ ] xz

**Comment by nieder** [comment]
Some packages that expect Big Sur to be v10.16 will need to fiddle with `MACOSX_DEPLOYMENT_TARGET` and setting `SYSTEM_VERSION_COMPAT=1` to make the system report 10.16 and not 11.0. As of right now, I've only found perl5162 to be the problem, but haven't tried much else.

**Comment by cooljeanius** [comment]
> This is to track issues that exist with the Big Sur betas:
> 
>     * [ ]  New arch field for arm64 ([Apple's chips will need a new architecture value #207](https://github.com/fink/fink/issues/207))
> 
>     * [x]  New macos11 SDK discovery ([Make sure VirtPackage.pm finds Big Sur SDKs #208](https://github.com/fink/fink/issues/208))
> 
>     * [x]  macOS version is now 11.0, not 10.16. ([BigSur reports as macOS 11 #209](https://github.com/fink/fink/issues/209))
> 
>     * [x]  new kernel version 20 ([Services.pm::get_darwin_equiv() assumes macOS v10.x #210](https://github.com/fink/fink/issues/210))
> 
>     * [x]  /usr/bin/perl is now 5.28.2
> 
>     * [x]  gperf-3.0.4 (part of libiconv build) FTBFS with Xcode12
> 
>     * [x]  java detection is broken ([Fink doesn't recognize system-java installs on BigSur #218](https://github.com/fink/fink/issues/218))

So, even though a lot of these have their checkboxes checked off here, the linked bugs are still open? Also, some additional checkboxes might be needed:

- [ ] #219 
- [ ] #236

**Comment by nieder** [comment]
closing this since all linked bugs are closed. We'll need to sync some .info files between fink and fink-dists, but that should be done in a clean issue specifically for that or for preparing to release.

**Comment by cooljeanius** [comment]
So... how are we supposed to perform the actual update? I have fink on my system from before I updated to Big Sur. Running `./inject.pl` from current git master says:
```
$ ./inject.pl
This script must be run under sudo, which requires your password.
Password:
Creating fink tarball...
tar -cf /opt/sw/src/fink-0.45.99.git.tar AUTHORS COPYING INSTALL INSTALL.html MANIFEST MANIFEST.SKIP Makefile NEWS README README.buildsystem README.html README.removing-fink-bld REVISION Release STYLE TODO USAGE USAGE.html VERSION bootstrap bootstrap-phase2.pl compiler_wrapper-10.6.in compiler_wrapper-10.7.in compiler_wrapper-10.9.in dpkg-checkall.sh fink-dpkg-status-cleanup.in fink-instscripts.in fink-scanpackages.in fink-virtual-pkgs.in fink.8.in fink.conf.5.in fink.csh fink.in fink.sh fink.shlibs g++-wrapper.in images/finkDoneFailed.png images/finkDonePassed.png images/finkPackageBuildFailed.png images/finkPackageBuildPassed.png images/finkPackageInstallationFailed.png images/finkPackageInstallationPassed.png images/finkPackageRemovalFailed.png images/finkPackageRemovalPassed.png inject.pl install.sh lockwait.in pathsetup.sh.in perlmod/Fink.pm.in perlmod/Fink/Base.pm perlmod/Fink/Bootstrap.pm perlmod/Fink/CLI.pm perlmod/Fink/Checksum.pm perlmod/Fink/Checksum/MD5.pm perlmod/Fink/Checksum/SHA1.pm perlmod/Fink/Checksum/SHA256.pm perlmod/Fink/Command.pm perlmod/Fink/Config.pm perlmod/Fink/Configure.pm perlmod/Fink/Engine.pm perlmod/Fink/Finally.pm perlmod/Fink/Finally/BuildConflicts.pm perlmod/Fink/Finally/Buildlock.pm perlmod/Fink/FinkVersion.pm.in perlmod/Fink/Mirror.pm perlmod/Fink/NetAccess.pm perlmod/Fink/Notify.pm perlmod/Fink/Notify/Growl.pm perlmod/Fink/Notify/QuickSilver.pm perlmod/Fink/Notify/Say.pm perlmod/Fink/Notify/Syslog.pm perlmod/Fink/Notify/XTerm.pm perlmod/Fink/Package.pm perlmod/Fink/PkgVersion.pm perlmod/Fink/Scanpackages.pm perlmod/Fink/SelfUpdate.pm perlmod/Fink/SelfUpdate/Base.pm perlmod/Fink/SelfUpdate/CVS.pm perlmod/Fink/SelfUpdate/git.pm perlmod/Fink/SelfUpdate/point.pm perlmod/Fink/SelfUpdate/rsync.pm perlmod/Fink/SelfUpdate/svn.pm perlmod/Fink/Services.pm perlmod/Fink/Status.pm perlmod/Fink/SysState.pm perlmod/Fink/Text/DelimMatch.pm perlmod/Fink/Text/ParseWords.pm perlmod/Fink/Tie/IxHash.pm perlmod/Fink/Validation.pm perlmod/Fink/VirtPackage.pm postinstall.pl.in pre-build-test.sh readme.en.html readme.es.html readme.fr.html readme.ja.html readme.pt.html readme.ru.html readme.zh.html setup.sh shlibs.default.in t/00compile.t t/10features/users_groups.t t/10features/volume.t t/Base/initialize.t t/Base/param.t t/Base/param_boolean.t t/CLI/capture.t t/Command/cat.t t/Command/chowname.t t/Command/commands.t t/Command/du_sk.t t/Command/exports.t t/Command/failure.t t/Command/touch.t t/Config/exports.t t/Config/failure.t t/Config/flag.t t/Config/load_save.t t/Config/options.t t/Config/param.t t/Config/verbosity_level.t t/Engine/fetch.t t/Engine/p0.info t/Engine/p1.info t/Engine/p2.info t/Engine/p3.info t/Engine/p4.info t/Finally/buildlocks.t t/Finally/finally.t t/FinkVersion/exports.t t/FinkVersion/version.t t/Mirror/exports.t t/Notify/exports.t t/Package/duplicate_fullname_trees/epoch1/finkinfo/duplicate-fullname.info t/Package/duplicate_fullname_trees/epoch1again/finkinfo/duplicate-fullname.info t/Package/duplicate_fullname_trees/epoch2/finkinfo/duplicate-fullname.info t/Package/duplicate_fullnames.t t/PkgVersion/get_perl.t t/PkgVersion/get_ruby.t t/PkgVersion/get_splitoffs-tree/finkinfo/p1.info t/PkgVersion/get_splitoffs-tree/finkinfo/p2.info t/PkgVersion/get_splitoffs-tree/finkinfo/p3.info t/PkgVersion/get_splitoffs.t t/PkgVersion/mp3-info-pm-1.01-1.info t/PkgVersion/non-consecutive-test.info t/PkgVersion/non-consecutive-test2.info t/PkgVersion/non_consecutive_source.t t/PkgVersion/opengl-rb18.info t/PkgVersion/sed-4.0.5-1.info t/PkgVersion/xml-parser-pm560-2.31-5.info t/SelfUpdate/last_done.t t/SelfUpdate/subclasses.t t/Services/eval_conditional.t t/Services/execute_nonroot_okay.t t/Services/expand_percent.t t/Services/prepare_script.t t/Services/spec2struct.t t/Services/version_cmp.t t/Text/DelimMatch/DelimMatch.t t/Text/ParseWords/ParseWords.t t/Text/ParseWords/taint.t t/Tie/IxHash/each-delete.t t/Tie/IxHash/ixhash.t t/Validation/_filename_versioning_cmp.t t/Validation/exports.t t/basepath/etc/fink.conf t/testmore.pl update-packages/README update/Makefile.in.in update/config.guess update/config.sub update/ltconfig update/ltmain.sh
Copying package description(s)...
/bin/mv /opt/sw/fink/dists/local/injected/finkinfo/fink.info /opt/sw/fink/dists/local/injected/finkinfo/fink.info.bak
Modifying package description...
/bin/chmod 644 /opt/sw/fink/dists/local/injected/finkinfo/*.*
Installing package...

/opt/sw/bin/fink install fink-0.45.99.git-20230729.1750
11.7 does not match the expected value of 10.16. Please run `fink selfupdate` to download a newer version of fink at /opt/sw/lib/perl5/Fink/Services.pm line 1369.
### execution of /opt/sw/bin/fink failed, exit code 29

Installing the new fink package failed. The description and the tarball were installed, though. You can retry at a later time by issuing the appropriate fink commands.
```
...and `fink selfupdate` itself fails with:
```
11.7 does not match the expected value of 10.16. Please run `fink selfupdate` to download a newer version of fink at /opt/sw/lib/perl5/Fink/Services.pm line 1369.
```

**Comment by nieder** [comment]
```
/opt/sw/bin/fink install fink-0.45.99.git-20230729.1750
11.7 does not match the expected value of 10.16. Please run `fink selfupdate` to download a newer version of fink at /opt/sw/lib/perl5/Fink/Services.pm line 1369.
### execution of /opt/sw/bin/fink failed, exit code 29
```

That should have been dealt with in b3c90bda7c60229ac9c108ff2042f8a20574e459 (which was committed the same day as your comment). Do you still have the failure, even after a fresh pull?

**Comment by cooljeanius** [comment]
> ```
> /opt/sw/bin/fink install fink-0.45.99.git-20230729.1750
> 11.7 does not match the expected value of 10.16. Please run `fink selfupdate` to download a newer version of fink at /opt/sw/lib/perl5/Fink/Services.pm line 1369.
> ### execution of /opt/sw/bin/fink failed, exit code 29
> ```
> 
> That should have been dealt with in [b3c90bd](https://github.com/fink/fink/commit/b3c90bda7c60229ac9c108ff2042f8a20574e459) (which was committed the same day as your comment). Do you still have the failure, even after a fresh pull?

Yes, it still happens:
```
$ ./inject.pl
This script must be run under sudo, which requires your password.
Creating fink tarball...
tar -cf /opt/sw/src/fink-0.45.99.git.tar AUTHORS COPYING INSTALL INSTALL.html MANIFEST MANIFEST.SKIP Makefile NEWS README README.buildsystem README.html README.removing-fink-bld REVISION Release STYLE TODO USAGE USAGE.html VERSION bootstrap bootstrap-phase2.pl compiler_wrapper-10.6.in compiler_wrapper-10.7.in compiler_wrapper-10.9.in dpkg-checkall.sh fink-dpkg-status-cleanup.in fink-instscripts.in fink-scanpackages.in fink-virtual-pkgs.in fink.8.in fink.conf.5.in fink.csh fink.in fink.sh fink.shlibs g++-wrapper.in images/finkDoneFailed.png images/finkDonePassed.png images/finkPackageBuildFailed.png images/finkPackageBuildPassed.png images/finkPackageInstallationFailed.png images/finkPackageInstallationPassed.png images/finkPackageRemovalFailed.png images/finkPackageRemovalPassed.png inject.pl install.sh lockwait.in pathsetup.sh.in perlmod/Fink.pm.in perlmod/Fink/Base.pm perlmod/Fink/Bootstrap.pm perlmod/Fink/CLI.pm perlmod/Fink/Checksum.pm perlmod/Fink/Checksum/MD5.pm perlmod/Fink/Checksum/SHA1.pm perlmod/Fink/Checksum/SHA256.pm perlmod/Fink/Command.pm perlmod/Fink/Config.pm perlmod/Fink/Configure.pm perlmod/Fink/Engine.pm perlmod/Fink/Finally.pm perlmod/Fink/Finally/BuildConflicts.pm perlmod/Fink/Finally/Buildlock.pm perlmod/Fink/FinkVersion.pm.in perlmod/Fink/Mirror.pm perlmod/Fink/NetAccess.pm perlmod/Fink/Notify.pm perlmod/Fink/Notify/Growl.pm perlmod/Fink/Notify/QuickSilver.pm perlmod/Fink/Notify/Say.pm perlmod/Fink/Notify/Syslog.pm perlmod/Fink/Notify/XTerm.pm perlmod/Fink/Package.pm perlmod/Fink/PkgVersion.pm perlmod/Fink/Scanpackages.pm perlmod/Fink/SelfUpdate.pm perlmod/Fink/SelfUpdate/Base.pm perlmod/Fink/SelfUpdate/CVS.pm perlmod/Fink/SelfUpdate/git.pm perlmod/Fink/SelfUpdate/point.pm perlmod/Fink/SelfUpdate/rsync.pm perlmod/Fink/SelfUpdate/svn.pm perlmod/Fink/Services.pm perlmod/Fink/Status.pm perlmod/Fink/SysState.pm perlmod/Fink/Text/DelimMatch.pm perlmod/Fink/Text/ParseWords.pm perlmod/Fink/Tie/IxHash.pm perlmod/Fink/Validation.pm perlmod/Fink/VirtPackage.pm postinstall.pl.in pre-build-test.sh readme.en.html readme.es.html readme.fr.html readme.ja.html readme.pt.html readme.ru.html readme.zh.html setup.sh shlibs.default.in t/00compile.t t/10features/users_groups.t t/10features/volume.t t/Base/initialize.t t/Base/param.t t/Base/param_boolean.t t/CLI/capture.t t/Command/cat.t t/Command/chowname.t t/Command/commands.t t/Command/du_sk.t t/Command/exports.t t/Command/failure.t t/Command/touch.t t/Config/exports.t t/Config/failure.t t/Config/flag.t t/Config/load_save.t t/Config/options.t t/Config/param.t t/Config/verbosity_level.t t/Engine/fetch.t t/Engine/p0.info t/Engine/p1.info t/Engine/p2.info t/Engine/p3.info t/Engine/p4.info t/Finally/buildlocks.t t/Finally/finally.t t/FinkVersion/exports.t t/FinkVersion/version.t t/Mirror/exports.t t/Notify/exports.t t/Package/duplicate_fullname_trees/epoch1/finkinfo/duplicate-fullname.info t/Package/duplicate_fullname_trees/epoch1again/finkinfo/duplicate-fullname.info t/Package/duplicate_fullname_trees/epoch2/finkinfo/duplicate-fullname.info t/Package/duplicate_fullnames.t t/PkgVersion/get_perl.t t/PkgVersion/get_ruby.t t/PkgVersion/get_splitoffs-tree/finkinfo/p1.info t/PkgVersion/get_splitoffs-tree/finkinfo/p2.info t/PkgVersion/get_splitoffs-tree/finkinfo/p3.info t/PkgVersion/get_splitoffs.t t/PkgVersion/mp3-info-pm-1.01-1.info t/PkgVersion/non-consecutive-test.info t/PkgVersion/non-consecutive-test2.info t/PkgVersion/non_consecutive_source.t t/PkgVersion/opengl-rb18.info t/PkgVersion/sed-4.0.5-1.info t/PkgVersion/xml-parser-pm560-2.31-5.info t/SelfUpdate/last_done.t t/SelfUpdate/subclasses.t t/Services/eval_conditional.t t/Services/execute_nonroot_okay.t t/Services/expand_percent.t t/Services/prepare_script.t t/Services/spec2struct.t t/Services/version_cmp.t t/Text/DelimMatch/DelimMatch.t t/Text/ParseWords/ParseWords.t t/Text/ParseWords/taint.t t/Tie/IxHash/each-delete.t t/Tie/IxHash/ixhash.t t/Validation/_filename_versioning_cmp.t t/Validation/exports.t t/basepath/etc/fink.conf t/testmore.pl update-packages/README update/Makefile.in.in update/config.guess update/config.sub update/ltconfig update/ltmain.sh
Copying package description(s)...
/bin/mv /opt/sw/fink/dists/local/injected/finkinfo/fink.info /opt/sw/fink/dists/local/injected/finkinfo/fink.info.bak
Modifying package description...
/bin/chmod 644 /opt/sw/fink/dists/local/injected/finkinfo/*.*
Installing package...

/opt/sw/bin/fink install fink-0.45.99.git-20230916.1727
11.7 does not match the expected value of 10.16. Please run `fink selfupdate` to download a newer version of fink at /opt/sw/lib/perl5/Fink/Services.pm line 1369.
### execution of /opt/sw/bin/fink failed, exit code 29

Installing the new fink package failed. The description and the tarball were installed, though. You can retry at a later time by issuing the appropriate fink commands.

$ fink selfupdate
11.7 does not match the expected value of 10.16. Please run `fink selfupdate` to download a newer version of fink at /opt/sw/lib/perl5/Fink/Services.pm line 1369.
```

**Comment by nieder** [comment]
What's the output of the commands
1. `sw_vers`
2. `uname -a`
3. `/opt/sw/bin/fink --version`
?

Is your Fink git source tree pointing to github.com/fink/fink or github.com/TheSin-/fink ? You can run the command `git remote -v` from the directory where you run `./inject.pl` from.

If I understand your system history correctly, you had something less than Big Sur (macOS 11) with Fink installed (tarball release or git version?), then you upgraded to Big Sur, upgraded to a Fink from git, and now `./inject.pl` and `fink selfupate` both fail with the 11.7/10.16 mismatch problem. Correct?

**Comment by cooljeanius** [comment]
> What's the output of the commands
> 
>    1. `sw_vers`
> 
>    2. `uname -a`
> 
>    3. `/opt/sw/bin/fink --version`
>        ?
> 
> 
> Is your Fink git source tree pointing to github.com/fink/fink or github.com/TheSin-/fink ? You can run the command `git remote -v` from the directory where you run `./inject.pl` from.
>

```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.7.10
BuildVersion:	20G1427
$ uname -a
Darwin Local-Admins-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 x86_64
$ /opt/sw/bin/fink --version
Package manager version: 0.45.2
Distribution version: selfupdate-git Sun Jan 17 18:34:37 2021, 10.15, x86_64
Trees: local/main stable/main local/injected

Copyright (c) 2001 Christoph Pfisterer
Copyright (c) 2001-2020 The Fink Package Manager Team
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
$ git remote -v
origin	https://github.com/cooljeanius/fink.git (fetch)
origin	https://github.com/cooljeanius/fink.git (push)
upstream	https://github.com/fink/fink.git (fetch)
upstream	https://github.com/fink/fink.git (push)
```

> If I understand your system history correctly, you had something less than Big Sur (macOS 11) with Fink installed (tarball release or git version?), then you upgraded to Big Sur, upgraded to a Fink from git, and now `./inject.pl` and `fink selfupate` both fail with the 11.7/10.16 mismatch problem. Correct?

I think it was from a tarball release originally, then I upgraded to Big Sur, and now I'm *trying* to update to a Fink from git, but it won't actually let me.

**Comment by nieder** [comment]
```
origin	https://github.com/cooljeanius/fink.git (fetch)
origin	https://github.com/cooljeanius/fink.git (push)
upstream	https://github.com/fink/fink.git (fetch)
upstream	https://github.com/fink/fink.git (push)
```
This says your git tree is from your fork (origin). Has your fork been updated to be up to date with upstream? The file `perlmod/Fink/Services.pm` should show an `if` statement in the function `sub get_osx_vers()` around line 1447 that mentions 11.7. If it only mentions 11.6 and 12.6, then it's not up to date.

**Comment by cooljeanius** [comment]
> ```
> origin	https://github.com/cooljeanius/fink.git (fetch)
> origin	https://github.com/cooljeanius/fink.git (push)
> upstream	https://github.com/fink/fink.git (fetch)
> upstream	https://github.com/fink/fink.git (push)
> ```
> 
> This says your git tree is from your fork (origin). Has your fork been updated to be up to date with upstream?

Yes, it has.

> The file `perlmod/Fink/Services.pm` should show an `if` statement in the function `sub get_osx_vers()` around line 1447 that mentions 11.7. If it only mentions 11.6 and 12.6, then it's not up to date.

Yes, I checked, and it looks the same.

**Comment by nieder** [comment]
I just noticed that your `fink --version` is reporting as 10.15, which makes sense given the update history. Try the following:
`fink reinstall fink`. Hopefully that might flip your Fink to realizing it's on 11.x now.

Are you setting the environement variable `SYSTEM_VERSION_COMPAT` anywhere (.bash_profile, etc) ? Setting this to 1 makes Big Sur report as 10.16 (like what the error is giving you), instead of 11.x that Fink is expecting. If it's being set, remove it.

If none of this works, can you attach the file Services.pm from the git tree you're trying to inject from?

**Comment by cooljeanius** [comment]
> I just noticed that your `fink --version` is reporting as 10.15, which makes sense given the update history. Try the following: `fink reinstall fink`. Hopefully that might flip your Fink to realizing it's on 11.x now.
>

```
$ fink reinstall fink
Password:
11.7 does not match the expected value of 10.16. Please run `fink selfupdate` to download a newer version of fink at /opt/sw/lib/perl5/Fink/Services.pm line 1369.
```
...actually wait, that gives me an idea, what if I just replace `/opt/sw/lib/perl5/Fink/Services.pm` manually? I'm going to try that next...

**Comment by cooljeanius** [comment]
> ...actually wait, that gives me an idea, what if I just replace `/opt/sw/lib/perl5/Fink/Services.pm` manually? I'm going to try that next...

ok yeah that seems to have worked
